#+STARTUP: showall

* About this repository

I use OfflineIMAP and [[https://github.com/lefcha/imapfilter][imapfilter]] to synchronise and filter work and
private emails, respectively. On top of OfflineIMAP I use [[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] (an
email client for Emacs) to manage my emails. This repository contains
my OfflineIMAP and imapfilter configuration files. My [[https://github.com/peterwvj/emacs-config-pvj/][mu4e
configuration]] is available in one of my other repositories.

* Repository structure

This repository contains my OfflineIMAP configuration files:

- =.offlineimaprc= My work (Microsoft Exchange) and private (Gmail)
  email account configuration. This file uses a small Python script,
  named =.offlineimap.py= (see next item) to read the authentication
  information that OfflineIMAP needs to synchronise emails for both
  accounts.

- =.offlineimap.py= A Python script that contains a single function
  that uses =gpg2= to read the password associated with the email
  account subject to synchronisation. The password is read from an
  encrypted file =~/.authinfo.gpg= (not included in this repository)
  that stores the authentication information (see below).

- =.imapfilter/config.lua= The imapfilter configuration file is
  written in [[https://www.lua.org/][Lua]] and currently set up to mark all spam mails as read
  (for both of my accounts). This configuration file uses the
  authentication information stored in =~/.authinfo.gpg= to filter the
  emails.

* Authentication information format

The =~/.authinfo.gpg= file stores the authentication information for
both accounts in the following format:

#+BEGIN_SRC
machine imap.gmail.com login peter.w.v.jorgensen@gmail.com port 993 password <password>
machine smtp.gmail.com login peter.w.v.jorgensen@gmail.com port 587 password <password>
machine imap.au.dk login uni\au219464 port 993 password <password>
machine asmtp.au.dk login uni\au219464 port 587 password <password>
#+END_SRC

* Credits

This OfflineIMAP configuration is inspired by areina's [[https://gist.github.com/areina/3879626][gist]]
